### ISSUE TITLE
the motor only goes on on full force, somethng in IN4073 needs to be fixed 

### ISSUE THREAD

**Issue by JBmiog** [JBmiog/QC-embedded#12]
in manual mode

**Comment by makis09917** [comment]
I fixed it, I print the values of the ae[] array as I press the different keyboard buttons and it works fine. 
I will share with you the new source files tomorrow.
The only thing is that the whole logic of how the motors work may need some corrections, but for the time being I believe its fine, so we need to focus on the new stuff we have to do.
