### ISSUE TITLE
 Issues after TA checking

### ISSUE THREAD

**Issue by hongjiawu** [JBmiog/QC-embedded#18]
1. No transitions when value changes
2. Blue LED frequency
3. Emergency Stop approach 
4. Delay

**Comment by makis09917** [comment]
1. FIXED
2. I will fix it
3. What do you mean?
4. FIXED. I set a flag inside the Rx_ISR of uart, then read the message and unset the flag.
   It seems that there is no delay now. I press buttons to change between modes and LEDs light on or light off instantaneously, completely different as compared to the older version. In addition by pressing the the buttons for the drone movements I can see the print-out of motor values instantaneously, like in the demo they had given to us. 

It remains to test on the actual drone.  (check fixed_branch)

**Comment by hongjiawu** [comment]
For the third one, I have already fixed it by enabling the button on joystick.

**Comment by JBmiog** [comment]
Fixed the blue led toggling
