### ISSUE TITLE
Joystick

### ISSUE THREAD

**Issue by hongjiawu** [JBmiog/QC-embedded#19]
1. Buttons
2. Senstivity

**Comment by JBmiog** [comment]
What is the issue / problem statement you are solving? How are you planning on solving this? Elaborating a bit more on this issue will enable us all to follow your progress and line of thoughts, so we can easily merge it when it is done! :)

**Comment by hongjiawu** [comment]
This issue will enable mode switch function on joystick as well. Besides, it will eliminate the yaw offset.

**Comment by hongjiawu** [comment]
Issues get fixed.
