### ISSUE TITLE
panic mode to safe mode transition

### ISSUE THREAD

**Issue by makis09917** [JBmiog/QC-embedded#22]
panic mode to safe mode from keyboard is ok

When battery is low and we enter panic mode due to that, we reach safe mode, but since the pc continues sending packets with "manual" info in the mode field we do circles forever.

We should insert a bat_high flag in safe mode and switch between modes when this flag is true. 

Same for connection

I will handle that!

**Comment by JBmiog** [comment]
Yeah, shall we also discuss soon about a protocol for drone to pc side? It'll allow us to effectivily transport information which we can display, rather than the unstructured way of printf statements. We then know on pc side what the battery status is.

**Comment by makis09917** [comment]
all transitions from panic mode to safe mode  (by keyboard pressing, battery low, or no connection) are implemented, it remains to test them in the actual drone. (@fixed_version branch)

**Comment by JBmiog** [comment]
donneeeee
